[package]
name = "hopwhy-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
hopwhy = { path = ".." }
libfuzzer-sys = "=0.4.13"

[[bin]]
name = "target_and_report"
path = "fuzz_targets/target_and_report.rs"
test = false
doc = false
bench = false
